language: node_js
node_js:
  - "8"
sudo: required
branches:
  only:
    - master
    - /^greenkeeper/.*$/
dist: trusty
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g ionic

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
