language: node_js
node_js:
  - “7”

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g ionic

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build --prod
  - xvfb-run npm run e2e
